/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2022-12-04 08:51:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("<title>Welcome</title>\n");
      out.write("\n");
      out.write("<!-- Font Icon -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"fonts/material-icon/css/material-design-iconic-font.min.css\">\n");
      out.write("\n");
      out.write("<!-- Main css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<input type=\"hidden\" id=\"status\"\n");
      out.write("\t\tvalue=\"");
      out.print(request.getAttribute("status"));
      out.write("\">\n");
      out.write("\t<div class=\"main\">\n");
      out.write("\n");
      out.write("\t\t<!-- Sing in  Form -->\n");
      out.write("\t\t<section class=\"sign-in\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"signin-content\">\n");
      out.write("\t\t\t\t\t<div class=\"signin-image\">\n");
      out.write("\t\t\t\t\t\t<figure>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/signin-image.jpg\" alt=\"sing up image\">\n");
      out.write("\t\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t\t<a href=\"registration.jsp\" class=\"signup-image-link\">Create an\n");
      out.write("\t\t\t\t\t\t\taccount</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"signin-form\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"form-title\">Log In</h2>\n");
      out.write("\t\t\t\t\t\t<form method=\"post\" action=\"login\" class=\"register-form\"\n");
      out.write("\t\t\t\t\t\t\tid=\"login-form\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"username\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"zmdi zmdi-account material-icons-name\"></i></label> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"username\" id=\"username\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Your Name\" required=\"required\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"password\"><i class=\"zmdi zmdi-lock\"></i></label> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"password\" name=\"password\" id=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Password\" required=\"required\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"forgotPassword.jsp\"> Forgot Password?</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"remember-me\" id=\"remember-me\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"agree-term\"  required = \"required\" /> <label for=\"remember-me\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"label-agree-term\"><span><span></span></span>Remember\n");
      out.write("\t\t\t\t\t\t\t\t\tme</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group form-button\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"signin\" id=\"signin\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-submit\" value=\"login\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t<div class=\"social-login\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"social-label\">Or login with</span>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"socials\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"display-flex-center zmdi zmdi-facebook\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"display-flex-center zmdi zmdi-twitter\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"display-flex-center zmdi zmdi-google\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</section>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- JS -->\n");
      out.write("\t<script src=\"vendor/jquery/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"js/main.js\"></script>\n");
      out.write("\t<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"alert/dist/sweetalert.css\">\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\tvar status = document.getElementById(\"status\").value;\n");
      out.write("\t\tif (status == \"failed\") {\n");
      out.write("\t\t\tswal(\"Sorry\", \"Wrong Username or Password\", \"error\");\n");
      out.write("\t\t}\n");
      out.write("\t\tif (status == \"invalidEmail\") {\n");
      out.write("\t\t\tswal(\"Sorry\", \"Please Enter Email\", \"error\");\n");
      out.write("\t\t}\n");
      out.write("\t\tif (status == \"invalidUpwd\") {\n");
      out.write("\t\t\tswal(\"Sorry\", \"Please Enter Password\", \"error\");\n");
      out.write("\t\t}\n");
      out.write("\t\tif (status == \"resetSuccess\") {\n");
      out.write("\t\t\tswal(\"Congrats\", \"Password is changed\", \"success\");\n");
      out.write("\t\t}\n");
      out.write("\t\tif (status == \"resetFailed\") {\n");
      out.write("\t\t\tswal(\"Sorry\", \"Password is not changed\", \"error\");\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("<!-- This templates was made by Colorlib (https://colorlib.com) -->\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
