/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2022-12-04 10:09:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("<title>Register</title>\n");
      out.write("\n");
      out.write("<!-- Font Icon -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"fonts/material-icon/css/material-design-iconic-font.min.css\">\n");
      out.write("\n");
      out.write("<!-- Main css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<input type=\"hidden\" id=\"status\" value = \"");
      out.print( request.getAttribute("status") );
      out.write("\">\n");
      out.write("\n");
      out.write("\t<div class=\"main\">\n");
      out.write("\n");
      out.write("\t\t<!-- Sign up form -->\n");
      out.write("\t\t<section class=\"signup\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"signup-content\">\n");
      out.write("\t\t\t\t\t<div class=\"signup-form\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"form-title\">Sign up</h2>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<form method=\"post\" action=\"register\" class=\"register-form\"\n");
      out.write("\t\t\t\t\t\t\tid=\"register-form\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"name\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"zmdi zmdi-account material-icons-name\"></i></label> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"name\" id=\"name\" placeholder=\"Your Name\"  required = \"required\"/>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"email\"><i class=\"zmdi zmdi-email\"></i></label> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"email\" name=\"email\" id=\"email\" placeholder=\"Your Email\" required = \"required\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"pass\"><i class=\"zmdi zmdi-lock\"></i></label> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"password\" name=\"pass\" id=\"pass\" placeholder=\"Password\" required = \"required\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"re-pass\"><i class=\"zmdi zmdi-lock-outline\"></i></label>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" name=\"re_pass\" id=\"re_pass\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Repeat your password\" required = \"required\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"contact\"><i class=\"zmdi zmdi-lock-outline\"></i></label>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"contact\" id=\"contact\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Contact no\" required = \"required\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"agree-term\" id=\"agree-term\" required = \"required\" \n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"agree-term\" /> <label for=\"agree-term\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"label-agree-term\"><span><span></span></span>I\n");
      out.write("\t\t\t\t\t\t\t\t\tagree all statements in the <a href=\"#\" class=\"term-service\">Terms\n");
      out.write("\t\t\t\t\t\t\t\t\t\tof service</a></label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group form-button\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"signup\" id=\"signup\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-submit\" value=\"register\" />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"signup-image\">\n");
      out.write("\t\t\t\t\t\t<figure>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/signup-image.jpg\" alt=\"sing up image\">\n");
      out.write("\t\t\t\t\t\t</figure>\n");
      out.write("\t\t\t\t\t\t<a href=\"login.jsp\" class=\"signup-image-link\">I am already\n");
      out.write("\t\t\t\t\t\t\tmember</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<!-- JS -->\n");
      out.write("\t<script src=\"vendor/jquery/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"js/main.js\"></script>\n");
      out.write("\t<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"alert/dist/sweetalert.css\">\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("  var status = document.getElementById(\"status\").value;\n");
      out.write("  if(status == \"success\"){\n");
      out.write("\t  swal(\"Congrats\", \"Account Created Successfully\", \"success\");\n");
      out.write("\t}\n");
      out.write("  if(status == \"invalidName\"){\n");
      out.write("\t  swal(\"Sorry\", \"Please Enter Name\", \"error\");\n");
      out.write("\t}\n");
      out.write("  if(status == \"invalidEmail\"){\n");
      out.write("\t  swal(\"Sorry\", \"Please Enter Email\", \"error\");\n");
      out.write("\t}\n");
      out.write("  if(status == \"invalidUpwd\"){\n");
      out.write("\t  swal(\"Sorry\", \"Please enter Password\", \"error\");\n");
      out.write("\t}\n");
      out.write("  if(status == \"invalidMobile\"){\n");
      out.write("\t  swal(\"Sorry\", \"Please Enter Mobile Number\", \"error\");\n");
      out.write("\t}\n");
      out.write("  if(status == \"invalidMobileLength\"){\n");
      out.write("\t  swal(\"Sorry\", \"Mobile Number should be of 10 digit\", \"error\");\n");
      out.write("\t}\n");
      out.write("  if(status == \"invalidConfirmPassword\"){\n");
      out.write("\t  swal(\"Sorry\", \"Password do not match\", \"error\");\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
